# Generated by Django 6.0.4 on 2026-04-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demouser',
            name='created_at',
        ),
    ]
