# Generated by Django 6.0.4 on 2026-04-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_demouser_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoUser',
        ),
    ]
